# Generated by Django 6.0.1 on 2026-01-29 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vendor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='google_maps_link',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='google_rating',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='poc_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='price_min',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.location'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='services',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.subcategory'),
        ),
    ]
